### ISSUE TITLE
Generated colors don't really match wallpaper

### ISSUE THREAD

**Issue by nclarius** [tantalising/kde-plasma-adaptive-wallpaper-accent-color#3]
An accent color is generated for every wallpaper, but often it does not really seem to match. With many wallpapers I get a kind of blue-green, even though the wallpaper doesn't really contain any green at all; something likes this with lighter and darker variations:   
![Screenshot_2021-12-19_22-56-03](https://user-images.githubusercontent.com/13196860/146692299-7edb94e1-e024-4fa6-b08c-e1888299e294.png)   

(The window outline is the accent color; the rest of the wallpaper looks the same as in the snippet.)

For some wallpaper the generated color looks matching though.  

Is there perhaps some color information from previous wallpapers somehow getting mixed in with the new wallpaper, or the picture not processed entirely? A cache issue on my end?

Or is this intended in order to provide contrast?

**Comment by tantalising** [comment]
The accent color algorithm that I use is not very optimized. For the sake of simplicity I didn't use any specialized library for this purpose. The accent color is really the average of all colors and if you image contains significant amount of black then the whole thing will shift towards black. Though this should not happen with every wallpaper, at least ,on my machine I get right accent almost 90j percent of time.
